/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robo.gltf 
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/robo.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Basic_cardboard} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Cardboard_Edge} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Eyes} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Pins} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Pipus} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.black_cardboard} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.button_1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.orange_cardboard} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.straws} />
      </group>
    </group>
  )
}

useGLTF.preload('/robo.gltf')
